module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      xs: '375px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
      '3xl': '1920px',
    },
    fontFamily: {
      sans: ['Montserrat', 'Roboto', 'sans-serif'],
      alternative: ['Montserrat Alternates', 'Roboto', 'sans-serif'],
    },
    extend: {
      colors: {
        dp: {
          'blue-500': '#0700F6',
          'blue-hover': '#322cff',
          'light-blue-400': '#99E2E7',
          'light-blue-800': '#33585A',
          'grayscale-100': '#FFFFFF',
          'grayscale-300': '#D5D9E3',
          'grayscale-800': '#2F3032',
          'yellow-500': '#FAF33E',
          'mint-500': '#4D8387',
          'green-500': '#669E83',
        },
      },
      fontSize: {
        'dp-headline-2-t': '48px',
        'dp-headline-3-t': '36px',
        'dp-headline-4-t': '34px',
        'dp-headline-2-m': '30px',
        'dp-headline-3-m': '24px',
        'dp-headline-4-m': '22px',
        'dp-headline-5-m': '20px',
        'dp-headline-6-m': '18px',
        'dp-bodytext-l-m': '16px',
        'dp-bodytext-m-dt': '14px',
      },
      spacing: {
        'header-mobile-padding': '90px',
        'header-web-padding': '150px',
        'content-padding': '75px',
        '3xs-gap': '10px',
        '2xs-gap': '15px',
        'xs-gap': '20px',
        'sm-gap': '25px',
        'md-gap': '35px',
        'lg-gap': '50px',
        'xl-gap': '100px',
        '2xl-gap': '150px',
        '3xl-gap': '175px',
      },
    },
  },
  variants: {},
  plugins: [],
};
